import AuthProvider from "./AuthProvider";
import "./globals.css";
import { Inter } from "next/font/google";
import SideBar from "@/components/SideBar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <AuthProvider>
      <html lang="en">
        {/* <body className={inter.className}> */}
        <body>
          {/* <NavMenu /> */}
          <div className="flex">
            <div className="bg-[#202123] max-w-xs h-screen overflow-y-auto md:min-w-[20rem]">
              {/* @ts-expect-error Server Component */}
              <SideBar />
            </div>
            <div className="bg-[#343541] flex-1">{children}</div>
          </div>
        </body>
      </html>
    </AuthProvider>
  );
}
