import AuthProvider from "./AuthProvider";
import NavMenu from "../components/navbar/NavMenu";
import "./globals.css";
import { Inter } from "next/font/google";
import SideBar from "@/components/SideBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <AuthProvider>
      <html lang="en">
        {/* <body className={inter.className}> */}
        <body>
          <NavMenu />
          {/* <div className="bg-[#202123] max-w-xs h-screen overflow-y-auto md:min-w-[20rem]"></div> */}
          <div className="bg-[#343541] flex-1">{children}</div>
        </body>
      </html>
    </AuthProvider>
  );
}
